// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exampleapp.Data;

#nullable disable

namespace exampleapp.Migrations
{
    [DbContext(typeof(ConachFieldDBContext))]
    [Migration("20240707155937_currentmigration")]
    partial class currentmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("exampleapp.Models.CoachField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abilities")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcademicBackground")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AcceptanceDefeat")
                        .HasColumnType("int");

                    b.Property<int>("BeliefDevelopment")
                        .HasColumnType("int");

                    b.Property<int>("CoachingAbility")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmotionalOpenness")
                        .HasColumnType("int");

                    b.Property<int>("EmotionalShare")
                        .HasColumnType("int");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("FeatureOriented")
                        .HasColumnType("int");

                    b.Property<int>("HaveTimetoListen")
                        .HasColumnType("int");

                    b.Property<string>("InternalCoachEffect")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KnowListening")
                        .HasColumnType("int");

                    b.Property<int>("KnowingEmpathy")
                        .HasColumnType("int");

                    b.Property<string>("LastTwoYearsExperience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadershipFeature")
                        .HasColumnType("int");

                    b.Property<int>("LikeCoaching")
                        .HasColumnType("int");

                    b.Property<int>("MotivationReasoning")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeopleWellness")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Positiveness")
                        .HasColumnType("int");

                    b.Property<string>("PossibleDevelopment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelfEducation")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Supporting")
                        .HasColumnType("int");

                    b.Property<int>("SupportingPeople")
                        .HasColumnType("int");

                    b.Property<int>("TimetoSpareforCoaching")
                        .HasColumnType("int");

                    b.Property<int>("ToleranceToAnything")
                        .HasColumnType("int");

                    b.Property<int>("WillingToBeCoached")
                        .HasColumnType("int");

                    b.Property<string>("WorkingDepartment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsEnrolled")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CoachField");
                });
#pragma warning restore 612, 618
        }
    }
}
